Strain
pyiron/pyiron_atomistics pull request #328
Opened 2021-08-25 16:50 UTC by samwaseda

Calculation of local strain.

Example:

```
from pyiron_atomistics import Project
pr = Project('.')
bulk = pr.create.structure.bulk('Fe', cubic=True)
structure = bulk.apply_strain(np.random.random((3,3))*0.1, return_box=True)
print(structure.analyse.get_strain(bulk)
```

Tests and DocStrings will follow

2021-08-27 11:12 UTC, liamhuber requested changes
`Strains` class has unit tests outstanding.

Otherwise a few nits, but the functionality seems great and I have no complaints about the overall architecture. As soon as the unit tests are there (and it's PEP8 linted!!!) I'm happy.

2021-08-27 11:12 UTC, liamhuber commented on pyiron_atomistics/atomistics/structure/strain.py
> +            raise ValueError('Crystal structure not recognized')
```suggestion
            raise ValueError(f'Crystal structure "{crystal_phase}" not recognized')
```

2021-08-27 11:12 UTC, liamhuber commented on pyiron_atomistics/atomistics/structure/strain.py
> +            dist += np.absolute(np.sum(dv*all_vecs[:,:1], axis=-1))
Why is the definition of `dist` split into two statements? It's not recursively defined or anything, it should all fit in one space. Alternatively, if the individual components have physical meaning that you want to make clear, define them separately with sensible names and then add `dist = physics_a + physics_b`.

2021-08-27 11:12 UTC, liamhuber commented on tests/atomistics/structure/test_analyse.py
> +        epsilon = 0.1*(np.random.random((3,3))-0.5)
```suggestion
        epsilon = 0.1*(np.random.random((3, 3))-0.5)
```

Please get a PEP8 linter you VIM(Emacs?)-nutcase 😝

2021-08-27 11:12 UTC, liamhuber commented on pyiron_atomistics/atomistics/structure/strain.py
> +        distances = np.linalg.norm(coords[:,:,None,:]-ref_coord[None,None,:,:], axis=-1)
```suggestion
        distances = np.linalg.norm(coords[:, :, None, :]-ref_coord[None, None, :, :], axis=-1)
```

PEP8

2021-08-27 11:12 UTC, liamhuber commented on pyiron_atomistics/atomistics/structure/strain.py
> +        D = np.linalg.inv(D)
```suggestion
        Dinverse = np.einsum('ij,ik->jk', self.ref_coord, self.ref_coord)
        D = np.linalg.inv(Dinverse)
```

The item in the first definition is the inverse of D, so let's just name it that. I guess this is slightly worse for performance since there's an extra variable kicking around, but its truthier to read and I trust the garbage collection to have our backs.

2021-08-27 11:12 UTC, liamhuber commented on pyiron_atomistics/atomistics/structure/strain.py
> +        J = np.einsum('nij,nik->njk', self.ref_coord[self._indices], self.coords)
Is there a similar pre-definition available here? I don't insist on this type of style change, but something about this pattern:

```python
mammal = 'reptile'
mammal = 'definitely not a ' + mammal
```

rubs me the wrong way.

2021-08-30 05:54 UTC, samwaseda commented
So now I finally installed a PEP8 plugin (which I'll hopefully regularly use from now on) so it should be fine :)

2021-08-30 07:52 UTC, pmrv approved these changes
I've made some formatting suggestions to play nice with sphinx, but looks good otherwise!

2021-08-30 07:52 UTC, pmrv commented on pyiron_atomistics/atomistics/structure/analyse.py
> +        ```
```suggestion
        >>> from pyiron_atomistics import Project
        >>> pr = Project('.')
        >>> bulk = pr.create.structure.bulk('Fe', cubic=True)
        >>> structure = bulk.apply_strain(np.random.random((3,3))*0.1, return_box=True)
        >>> structure.analyse.get_strain(bulk)
```

2021-08-30 07:52 UTC, pmrv commented on pyiron_atomistics/atomistics/structure/analyse.py
> +        - This strain is not the same as the strain applied in `Atoms.apply_strain`, which
```suggestion
        .. attention:: Differs from :meth:`.Atoms.apply_strain`!
            This strain is not the same as the strain applied in `Atoms.apply_strain`, which
```

2021-08-30 07:52 UTC, pmrv commented on pyiron_atomistics/atomistics/structure/strain.py
> +    strain = (F^T x F - 1)/2
```suggestion
    >>> strain = (F^T x F - 1)/2
```

2021-08-30 07:52 UTC, pmrv commented on pyiron_atomistics/atomistics/structure/strain.py
> +    ```
```suggestion
    >>> from pyiron_atomistics import Project
    >>> pr = Project('.')
    >>> bulk = pr.create.structure.bulk('Fe', cubic=True)
    >>> structure = bulk.apply_strain(np.random.random((3,3))*0.1, return_box=True)
    >>> Strain(structure, bulk).strain
```

2021-09-03 08:13 UTC, merged