Get structure fast
pyiron/pyiron_atomistics pull request #46
Opened 2021-01-24 14:51 UTC by pmrv

See #41.

This cuts the time on the same sample structure down to ~2s.  There's a similar overhead (~.5s) for other properties of `GenericInteractiveOutput` that are read via `_key_from_property`.  Pending feedback on #45 I'll cut that too.  I'll assume the rest is due to us reading the full arrays from HDF5 and then indexing them even if we only need a tiny part of them.  But to leverage that we'd have to touch HDF5 code and anyways the current speed up is enough to make it bearable for the POTENTIALS workshop.

For some reason this patch also makes the waiting time on the SQL connection disappear.

Example trace after the patch
```
         70225 function calls (69858 primitive calls) in 1.956 seconds

   Ordered by: internal time
   List reduced from 1008 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      115    0.803    0.007    1.309    0.011 {built-in method numpy.array}
        8    0.504    0.063    0.505    0.063 /u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py:947(read_direct)
        2    0.304    0.152    0.304    0.152 {method 'tolist' of 'numpy.ndarray' objects}
       14    0.155    0.011    0.156    0.011 {built-in method psycopg2._psycopg._connect}
       14    0.049    0.003    0.049    0.003 {method 'execute' of 'psycopg2.extensions.cursor' objects}
      124    0.021    0.000    0.024    0.000 {method '_g_new' of 'tables.hdf5extension.File' objects}
        2    0.011    0.005    0.545    0.273 /u/zora/software/pyiron_atomistics/pyiron_atomistics/atomistics/job/interactive.py:477(cells)
       14    0.008    0.001    0.008    0.001 {method 'rollback' of 'psycopg2.extensions.connection' objects}
      286    0.004    0.000    0.004    0.000 {method '_g_get_objinfo' of 'tables.hdf5extension.Group' objects}
     5548    0.004    0.000    0.004    0.000 /u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tables/group.py:838(__setattr__)
```

2021-01-24 15:11 UTC, jan-janssen requested changes
I am aware that we do not have the required unit tests, but I have the feeling we are missing some case if we remove the property part. The cases from my memory are: 

- some output already written to the HDF5 file `[output/interactive]`, some output in the cache - this seems to be handled correctly. 
- but for the case that the job was executed previously and the output is already copied to `[output/generic]` then we need to call the property to get this information, this is no longer included in the new version.

2021-01-24 17:03 UTC, pmrv commented on pyiron_atomistics/atomistics/job/interactive.py
> +            fetched = getattr(super(), key)
Loading from `output/generic` should be handled here, but I'll be honest and say that I didn't do testing beyond my sample notebook.

2021-02-08 19:21 UTC, pmrv commented
I've checked that it works with interactive jobs during and after the run as well as after reloading with the attached notebook.  Ideally I'd want to also look into #45, but I don't understand the code well enough and lack time for it.

2021-02-12 14:49 UTC, jan-janssen approved these changes
Looks good to me - I guess adding the integration tests can be done in a separate pull request

2021-03-18 08:45 UTC, merged