fix vasp potential
pyiron/pyiron_atomistics pull request #554
Opened 2022-03-01 17:51 UTC by jan-janssen

2022-03-01 18:36 UTC, jan-janssen commented
Somehow `concat` is not the same as `append`:
```
df = pd.DataFrame({"A": [1], "B": [2]})
df.append(pd.Series([3, 4], index=["A", "C"]), ignore_index=True) != pd.concat([df, pd.Series([3, 4], index=["A", "C"])])
```

2022-03-01 21:55 UTC, sudarsan-surendralal requested changes
For `concat` to work, you should convert the series to a dataframe before you apply the function

2022-03-01 21:55 UTC, sudarsan-surendralal commented on pyiron_atomistics/atomistics/structure/periodic_table.py
> +            )
```suggestion
            self.dataframe = pandas.concat(
                [self.dataframe, parent_element_data_series.to_frame().T],
            )
```

2022-03-01 21:55 UTC, sudarsan-surendralal commented on pyiron_atomistics/vasp/potential.py
> +            self._default_df = pandas.concat([self._default_df, ds])
```suggestion
            self._default_df = pandas.concat([self._default_df, ds.to_frame().T])
```

2022-03-01 23:59 UTC, sudarsan-surendralal approved these changes
After some changes and testing, the changes look okay

2022-03-02 02:26 UTC, jan-janssen commented
> After some changes and testing, the changes look okay

Perfect - thanks a lot

2022-03-02 02:26 UTC, merged